output:	main.o	DecisionTreeNode.o	DecisionTree.o
	g++	main.o	DecisionTreeNode.o	DecisionTree.o -o	hw2	-std=c++11

main.o:	main.cpp
	g++	-c	main.cpp	-std=c++11


DecisionTreeNode.o:	DecisionTreeNode.cpp	DecisionTreeNode.h
	g++	-c	DecisionTreeNode.cpp	-std=c++11


DecisionTree.o:	DecisionTree.cpp	DecisionTree.h
	g++	-c	DecisionTree.cpp	-std=c++11
