output:	main.o	FriendNet.o	List.o Queue.o
	g++	main.o	FriendNet.o List.o Queue.o -o	hw5	-std=c++11

main.o:	main.cpp
	g++	-c	main.cpp	-std=c++11


FriendNet.o:	FriendNet.cpp	FriendNet.h
	g++	-c	FriendNet.cpp	-std=c++11


List.o:	List.cpp	List.h
	g++	-c	List.cpp	-std=c++11

Queue.o:	Queue.cpp	Queue.h
	g++	-c	Queue.cpp	-std=c++11
